  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/golang:latest
      working_directory: ~/repo
      
      steps:
        - checkout # check out the code in the project directory
        - run:
            name: Install nodejs
            command: |
              sudo apt update && sudo apt install nodejs -y
        - run:
            name: Install yarn
            command: |
              curl -o- -L https://yarnpkg.com/install.sh | bash
        - run:
            name: yarn install
            command: |
              export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
              bash scripts/yarn_install.sh
        - run: 
            name: Build web-app
            command: |
              bash scripts/build_webapp.sh
        - run:
            name: Build service
            command: |
              bash scripts/build_service.sh