
name: CI
on: [push]

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      
      - name: Check out code
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
            go-version: 1.13

      - name: Go build
        run: |
          go build -o culaccino.out ./src/main.go

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.1
          with:
            node-version: 13.13.0
      
      - name: Npm install
        run: |
          cd ./theme && npm install

      - name: Build react
        run: |
          cd ./theme && npm run build
