
name: CI
on: [push]

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: Check out code
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      
      - name: Go build
        run: |
          go build -o culaccino.out ./src/main.go